# Generated by Django 4.1 on 2022-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [  # every migration comntains muultiple operations
        migrations.CreateModel( # frisrt operation
            name='Product',  # evry realistic table must have an id frame to uniquely identify the records in database
    
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
